name: Generate ASCII Artwork

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_job:
    name: Primer trabajo para construir
    runs-on: ubuntu-latest
    steps:  # ✅ debe ser 'steps'
      - name: Install Cowsay program
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Execcute Cowsay CMD
        run: |
          ls -ltra
          cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt
#          ./ascii-script.sh

      - name: Sleep for 30 seconds
        run: sleep 30 

  test_job:
    name: Segundo trabajo de prueba
    runs-on: ubuntu-latest
    needs: build_job  # Requiere que el primer job se ejecute para poder continuar
    steps:  # ✅ debe ser 'steps'
      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Test File Exist
        run: |
          ls -la
          grep -i dragon dragon.txt

  deploy_job:
    name: Tercer trabajo despliegue
    runs-on: ubuntu-latest
    needs: [test_job] # Se puede insertar varios jobs para que el proceso se ejecute
    steps:  # ✅ debe ser 'steps'
      - name: Read File
        run: cat dragon.txt

      - name: Deploy
        run: |
          echo Deploying...
