name: Generate ASCII Artwork

on:
  push:
    branches:
      - main
      - dev

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:  # ✅ debe ser 'steps'
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt

      - name: Test File Exist
        run: grep -i "dragon" dragon.txt
      
      - name: List Repo Files
        run: ls -ltra